#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PlivanjeMobileApp.Resource", IsApplication=true)]

namespace PlivanjeMobileApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_in_right = global::PlivanjeMobileApp.Resource.Animation.slide_in_right;
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_out_left = global::PlivanjeMobileApp.Resource.Animation.slide_out_left;
			global::Xamarin.Auth._MobileServices.Resource.Drawable.ic_arrow_back = global::PlivanjeMobileApp.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth._MobileServices.Resource.Id.webview = global::PlivanjeMobileApp.Resource.Id.webview;
			global::Xamarin.Auth._MobileServices.Resource.Layout.activity_webview = global::PlivanjeMobileApp.Resource.Layout.activity_webview;
			global::Xamarin.Auth._MobileServices.Resource.String.ApplicationName = global::PlivanjeMobileApp.Resource.String.ApplicationName;
			global::Xamarin.Auth._MobileServices.Resource.String.Hello = global::PlivanjeMobileApp.Resource.String.Hello;
			global::Xamarin.Auth._MobileServices.Resource.String.title_activity_webview = global::PlivanjeMobileApp.Resource.String.title_activity_webview;
			global::PCLCrypto.Resource.String.ApplicationName = global::PlivanjeMobileApp.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::PlivanjeMobileApp.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060002
			public const int text_size_large = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int text_size_medium = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int text_size_small = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int main_image = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001b
			public const int autocomplete_plivac = 2131296283;
			
			// aapt resource value: 0x7f090008
			public const int godina = 2131296264;
			
			// aapt resource value: 0x7f090010
			public const int imageView1 = 2131296272;
			
			// aapt resource value: 0x7f09000a
			public const int largeText1 = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int linearlayout1 = 2131296265;
			
			// aapt resource value: 0x7f090015
			public const int listView1 = 2131296277;
			
			// aapt resource value: 0x7f09000d
			public const int listViewLayout = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int mainText = 2131296270;
			
			// aapt resource value: 0x7f09000b
			public const int mediumText1 = 2131296267;
			
			// aapt resource value: 0x7f09002c
			public const int menu_index = 2131296300;
			
			// aapt resource value: 0x7f09002e
			public const int menu_klubovi = 2131296302;
			
			// aapt resource value: 0x7f09002d
			public const int menu_natjecanja = 2131296301;
			
			// aapt resource value: 0x7f09002f
			public const int menu_plivaci = 2131296303;
			
			// aapt resource value: 0x7f090030
			public const int menu_rekordi = 2131296304;
			
			// aapt resource value: 0x7f090003
			public const int mjesto = 2131296259;
			
			// aapt resource value: 0x7f090007
			public const int naziv = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int nazivKluba = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int plivaci = 2131296261;
			
			// aapt resource value: 0x7f090020
			public const int plivacijunbut = 2131296288;
			
			// aapt resource value: 0x7f090022
			public const int plivacikadbut = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int plivacimjunbut = 2131296289;
			
			// aapt resource value: 0x7f090023
			public const int plivacimkadbut = 2131296291;
			
			// aapt resource value: 0x7f09001f
			public const int plivacimsenbut = 2131296287;
			
			// aapt resource value: 0x7f090024
			public const int plivacipocbut = 2131296292;
			
			// aapt resource value: 0x7f09001e
			public const int plivacisenbut = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int plivacivetbut = 2131296285;
			
			// aapt resource value: 0x7f090016
			public const int podaci = 2131296278;
			
			// aapt resource value: 0x7f09000c
			public const int progressBar1 = 2131296268;
			
			// aapt resource value: 0x7f090028
			public const int rekordimbut = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int rekordizbut = 2131296297;
			
			// aapt resource value: 0x7f090019
			public const int rezultati = 2131296281;
			
			// aapt resource value: 0x7f09001c
			public const int searchbut = 2131296284;
			
			// aapt resource value: 0x7f09000f
			public const int secondText = 2131296271;
			
			// aapt resource value: 0x7f09001a
			public const int sezone = 2131296282;
			
			// aapt resource value: 0x7f090017
			public const int sezonebutton = 2131296279;
			
			// aapt resource value: 0x7f090004
			public const int spinner = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int spol = 2131296262;
			
			// aapt resource value: 0x7f090011
			public const int textArea1 = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int textArea2 = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int textArea3 = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int textArea4 = 2131296276;
			
			// aapt resource value: 0x7f090025
			public const int textArea5 = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int textArea6 = 2131296294;
			
			// aapt resource value: 0x7f090027
			public const int textArea7 = 2131296295;
			
			// aapt resource value: 0x7f09002a
			public const int textView1 = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int toolbar = 2131296299;
			
			// aapt resource value: 0x7f090001
			public const int toolbarIncluded = 2131296257;
			
			// aapt resource value: 0x7f090018
			public const int utrkebutton = 2131296280;
			
			// aapt resource value: 0x7f090000
			public const int webview = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ClubDetailsLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ClubSwimmerLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int KluboviLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListViewLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NatjecanjaLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NatjecanjeDetaljiLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Plivac = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Plivaci = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PlivaciUtrkaOsnovnoLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PregledPlivaca = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PrikazRekordiLayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Rekordi = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int searchListItem = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SearchResultsLayout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SezonaPlivaca = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int toolbar = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int UtrkaDetaljiLayout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int UtrkaOsnovnoLayout = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int top_menus = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int sezona_prompt = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int title_activity_webview = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
