#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PlivanjeMobileApp.Resource", IsApplication=true)]

namespace PlivanjeMobileApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_in_right = global::PlivanjeMobileApp.Resource.Animation.slide_in_right;
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_out_left = global::PlivanjeMobileApp.Resource.Animation.slide_out_left;
			global::Xamarin.Auth._MobileServices.Resource.Drawable.ic_arrow_back = global::PlivanjeMobileApp.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth._MobileServices.Resource.Id.webview = global::PlivanjeMobileApp.Resource.Id.webview;
			global::Xamarin.Auth._MobileServices.Resource.Layout.activity_webview = global::PlivanjeMobileApp.Resource.Layout.activity_webview;
			global::Xamarin.Auth._MobileServices.Resource.String.ApplicationName = global::PlivanjeMobileApp.Resource.String.ApplicationName;
			global::Xamarin.Auth._MobileServices.Resource.String.Hello = global::PlivanjeMobileApp.Resource.String.Hello;
			global::Xamarin.Auth._MobileServices.Resource.String.title_activity_webview = global::PlivanjeMobileApp.Resource.String.title_activity_webview;
			global::PCLCrypto.Resource.String.ApplicationName = global::PlivanjeMobileApp.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::PlivanjeMobileApp.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060002
			public const int text_size_large = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int text_size_medium = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int text_size_small = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_back = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int godina = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int largeText1 = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int linearlayout1 = 2131165192;
			
			// aapt resource value: 0x7f070016
			public const int listView1 = 2131165206;
			
			// aapt resource value: 0x7f07000c
			public const int listViewLayout = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int mainklubovibut = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int mainnatjecanjabut = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int mainplivacibut = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int mainrekordibut = 2131165200;
			
			// aapt resource value: 0x7f07000a
			public const int mediumText1 = 2131165194;
			
			// aapt resource value: 0x7f070011
			public const int mediumTextLayout = 2131165201;
			
			// aapt resource value: 0x7f070002
			public const int mjesto = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int naziv = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int nazivKluba = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int plivaci = 2131165188;
			
			// aapt resource value: 0x7f07001c
			public const int plivacijunbut = 2131165212;
			
			// aapt resource value: 0x7f07001e
			public const int plivacikadbut = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int plivacimjunbut = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int plivacimkadbut = 2131165215;
			
			// aapt resource value: 0x7f07001b
			public const int plivacimsenbut = 2131165211;
			
			// aapt resource value: 0x7f070020
			public const int plivacipocbut = 2131165216;
			
			// aapt resource value: 0x7f07001a
			public const int plivacisenbut = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int plivacivetbut = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int podaci = 2131165207;
			
			// aapt resource value: 0x7f07000b
			public const int progressBar1 = 2131165195;
			
			// aapt resource value: 0x7f070024
			public const int rekordimbut = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int rekordizbut = 2131165221;
			
			// aapt resource value: 0x7f070018
			public const int sezone = 2131165208;
			
			// aapt resource value: 0x7f070003
			public const int spinner = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int spol = 2131165189;
			
			// aapt resource value: 0x7f070012
			public const int textArea1 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int textArea2 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int textArea3 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int textArea4 = 2131165205;
			
			// aapt resource value: 0x7f070021
			public const int textArea5 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int textArea6 = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int textArea7 = 2131165219;
			
			// aapt resource value: 0x7f070000
			public const int webview = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ClubDetailsLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ClubSwimmerLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int KluboviLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListViewLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MediumTextLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NatjecanjaLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int NatjecanjeDetaljiLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Plivac = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Plivaci = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PlivaciUtrkaOsnovnoLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PregledPlivaca = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PrikazRekordiLayout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Rekordi = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SezonaPlivaca = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int UtrkaDetaljiLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int UtrkaOsnovnoLayout = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int sezona_prompt = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int title_activity_webview = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
